backend:
  name: github
  repo: incubateur-territoires/territoires.store

media_folder: "static/uploads"
public_folder: "/uploads"

# when using the default proxy server port
local_backend: true

collections:
  - name: "services"
    label: "Service"
    folder: "content/services"
    create: true
    slug: "{{service}}"
    fields:
      - {label: "Service", name: "service", widget: "string"}
      - {label: "Contact", name: "contact", widget: "string"}
      - {label: "URL", name: "url", widget: "string", required: false}
      - {label: "Action", name: "action", widget: "string"}
      - label: "Thématique"
        name: "thematique"
        widget: "select"
        multiple: true
        options: ["Mobilité", "Déchets", "Logement", "Démarches administratives", "Aides pour collectivités", "Accessibilité", "Emploi et Entreprise", "Données", "Urbanisme", "Solidarité", "Agriculture"]
        default: []
