backend:
  name: github
  repo: incubateur-territoires/territoires.store

media_folder: "static/uploads"
public_folder: "/uploads"

# when using the default proxy server port
local_backend: true

local_backend:
  # when using a custom proxy server port
  url: http://localhost:8082/api/v1
  # when accessing the local site from a host other than 'localhost' or '127.0.0.1'
  allowed_hosts: ['192.168.0.1']

collections:
  - name: "services"
    label: "Service"
    folder: "content/services"
    create: true
    slug: "{{startup}}"
    fields:
      - {label: "Startup", name: "startup", widget: "string"}
      - {label: "Contact", name: "contact", widget: "string"}
      - {label: "URL", name: "url", widget: "string"}
      - {label: "Action", name: "action", widget: "string"}
      - label: "Thématique"
        name: "thématique"
        widget: "select"
        multiple: true
        options: ["Mobilité", "Déchets", "Logement", "Démarches administratives", "Aides pour collectivités", "Accessibilités", "Emploi et Entreprise", "Données", "Urbanisme", "Solidarité", "Agriculture"]
        default: []
